project_id = "fyxvqxvvarnrbmkrkaxq"

[functions.generate-image]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.check-credits]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
